'use client'
import { useEffect, useState } from 'react'
import { Check, Home, X } from 'lucide-react'
import { IHNS_APPS, type IhnsAppId } from '@/lib/ihnsApps'
function WaffleIcon() { const dots = [3, 10, 17]; return <svg width="20" height="20" viewBox="0 0 20 20" fill="currentColor" aria-hidden>{dots.flatMap(cx => dots.map(cy => <circle key={`${cx}-${cy}`} cx={cx} cy={cy} r="1.9" />))}</svg> }
export function AppSwitcher({ current }: { current: IhnsAppId }) {
  const [open, setOpen] = useState(false)
  useEffect(() => { if (!open) return; const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') setOpen(false) }; document.addEventListener('keydown', onKey); return () => document.removeEventListener('keydown', onKey) }, [open])
  return <><button type="button" onClick={() => setOpen(true)} title="Các ứng dụng của iHNS" className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-gray-600 hover:bg-gray-100"><WaffleIcon /></button>{open && <div className="fixed inset-0 z-[100]"><div className="absolute inset-0 bg-black/30" onClick={() => setOpen(false)} /><aside className="absolute right-4 top-14 w-[min(92vw,340px)] rounded-3xl bg-[#f3f6fc] p-3 shadow-2xl ring-1 ring-gray-200"><div className="flex items-center justify-between px-2 pb-2"><p className="text-sm font-bold text-gray-700">Ứng dụng iHNS</p><button type="button" onClick={() => setOpen(false)} className="rounded-full p-1.5 text-gray-400 hover:bg-white"><X size={17} /></button></div><div className="grid grid-cols-3 gap-x-2 gap-y-5 rounded-2xl bg-white px-3 py-5">{IHNS_APPS.map(({ id, label, href, Icon, gradient }) => <a key={id} href={href} className="flex flex-col items-center gap-2 rounded-xl py-2 text-center hover:bg-gray-50"><span className="relative"><span className={`flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br ${gradient} text-white shadow-sm`}><Icon size={23} /></span>{id === current && <span className="absolute -bottom-1 -right-1 flex h-5 w-5 items-center justify-center rounded-full border-2 border-white bg-green-500 text-white"><Check size={10} strokeWidth={3} /></span>}</span><span className="text-xs font-medium text-gray-700">{label}</span></a>)}</div><a href="https://ihns.vn" className="mt-2 flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-medium text-gray-600 hover:bg-white"><Home size={15} />Trang chủ iHNS</a></aside></div>}</>
}
